### ISSUE TITLE
pronunciation exceptions need documentation with examples

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#105]
I've just fixed exception dictionary in bdf8b9e5fc262dad826ec2648ca7ffec096adf87 . 
I've just documented the German phoneset in https://github.com/dialogos-project/dialogos/wiki/Ausnahmew%C3%B6rterbuch, any takers for English?

**Comment by alexanderkoller** [comment]
Would it be too easy to hope that English just uses these?

https://en.wikipedia.org/wiki/SAMPA_chart_for_English

**Comment by timobaumann** [comment]
yes. it's the phoneset that is used by CMUdict instead: http://www.speech.cs.cmu.edu/cgi-bin/cmudict?in=Dialog+O+S

**Comment by alexanderkoller** [comment]
A rudimentary page on pronunciation dictionaries in English is now available here: https://github.com/dialogos-project/dialogos/wiki/Pronunciation-Dictionary

It would be cool if someone who knows more about this than me (Timo?) could finish it.
