### ISSUE TITLE
Built-in functions currentDate() and currentTime() are mixed up in documentation

### ISSUE THREAD

**Issue by kastein** [dialogos-project/dialogos#116]
In the German documentation of the built-in functions the returned structures of currentDate() and currentTime are mixed up: 

struct currentDate()
Gibt das momentane Datum als Struktur der Form { h:int, m:int } zurück.

struct currentTime()
Gibt die momentane Uhrzeit als Struktur der Form { day:int, month:int, year:int } zurück.

**Comment by timobaumann** [comment]
@kastein would you be willing to fix that yourself if we give you write access to the wiki? thanks.

**Comment by kastein** [comment]
Yes, I can fix it.

**Comment by timobaumann** [comment]
@kastein you should now have the appropriate permissions to edit wiki pages, let me know if it doesn't work

**Comment by kastein** [comment]
I'm not sure if I have the permission now because I couldn't find out how to edit the wiki. 
I was looking for the edit button but couldn't find one. Do I have to clone it and edit it locally?

**Comment by alexanderkoller** [comment]
The "Edit" button should be in the top right corner of the window, next to the green "New Page" button; to the right of the Wiki page title and above the page list. See the screenshot.

Can you see it?

<img width="1377" alt="screen shot 2018-11-19 at 16 03 01" src="https://user-images.githubusercontent.com/8291392/48715158-aa920f00-ec14-11e8-8b9f-b495231206e0.png">

**Comment by kastein** [comment]
No for me it looks like that
<img width="960" alt="unbenannt" src="https://user-images.githubusercontent.com/36165516/48715482-65baa800-ec15-11e8-9d28-6caac0a21136.PNG">

**Comment by timobaumann** [comment]
@kastein , can you try again?

**Comment by kastein** [comment]
Now it works, thank you. I fixed it.

**Comment by akoehn** [comment]
Thank you!

**Comment by timobaumann** [comment]
stay in the flow! fix the next documentation issue ;-)
