### ISSUE TITLE
Operator ::

### ISSUE THREAD

**Issue by urpeter** [dialogos-project/dialogos#118]
In the documentation on Operators on: https://github.com/dialogos-project/dialogos/wiki/Expressions
there is the "::" Operator but bla::blub doesn't work with my two variables bla = "hello", blub = [].

**Comment by timobaumann** [comment]
what happens instead?

**Comment by alexanderkoller** [comment]
Hi Timo, this is in response to a question I asked Mr. Peter earlier, regarding his use of the :: operator in a script that didn't execute correctly.

@urpeter I just double-checked this, and the :: operator actually does work as advertised. The attached script illustrates it. When I said a couple of days ago that :: does not exist and you should use "append" instead, I was wrong.

Could you say again in what way :: doesn't work?

[script.dos.zip](https://github.com/dialogos-project/dialogos/files/2604647/script.dos.zip)

**Comment by alexanderkoller** [comment]
Ideally by attaching a concrete, minimal dialog file?

**Comment by timobaumann** [comment]
I close this given that @alexanderkoller could not replicate the issue (and to stay <50 open issues)
