### ISSUE TITLE
Plus operator in DirectGrammars

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#121]
According to our analysis (see #109), the patterns of a DirectGrammar can be any RHS of an ABNF rule (see #120). We have confirmed that the Kleene star (*) works correctly, but the plus (+) operator doesn't seem to work. Instead, the pattern behaves as if the + wasn't there.

We should figure out what's going on and, if necessary, submit a bug report to Sphinx. Some things to do:

- Check if the plus operator is only broken in DirectGrammars or also in hand-written grammars.
- Check if we translate the plus operator correctly when translating from ABNF to JSGF.
- If it's not our fault, file a Sphinx bug report with a minimal example.

**Comment by timobaumann** [comment]
works nicely in Sphinx, see test in eaac4605c54772a2e89e7fc29cb1b6f778ccec3a

**Comment by timobaumann** [comment]
I traced this to the URL-encoding that we use to pass the grammar to Sphinx, looking for the best solution to url-encode a `+`.

**Comment by timobaumann** [comment]
fixed in c5e2d8199c64b142cd7b78ad5c78bbe07fc895a9

**Comment by alexanderkoller** [comment]
Beautiful!

Record it in the CHANGELOG, too?
