### ISSUE TITLE
nodes should focus content-specific properties tab instead of "general" tab on first call to properties

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#122]
it's super annoying: for every node I create, I have to switch from the super-useful tab that allows me to change the colors and name to the even more useful tabs.ge

We could either 
(a) move the general tab to the right by appending it last (instead of first), or 
(b) initially focusing the second tab instead of the first (under the assumption that there are always two tabs -- may need to include a safety check and set it to min(2,number-of-tabs).

This must be somewhere in Node.java

**Comment by alexanderkoller** [comment]
I like this. Especially (a).

**Comment by timobaumann** [comment]
you implement, I add to changelog?

**Comment by timobaumann** [comment]
(attempting to learn how to get tenure...)

**Comment by alexanderkoller** [comment]
It's not a high priority for me, compared to some other issues that we have open. If it annoys you, go ahead and fix it. :) Otherwise, someone will eventually find it annoying enough to make the change.
