### ISSUE TITLE
Recognizer becomes weird after cancellation

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#123]
Sometimes, I observe the following behavior:

1. Open an ASR node and click on "Try" to try out the speech recognizer.
2. Wait until the recognizer has been loaded and then cancel the recognition.
3. Click "Try" again.
4. The ASR window opens very briefly and then is closed again.

This doesn't seem entirely reproducible, but we should keep an eye on it and fix it.

**Comment by alexanderkoller** [comment]
@timobaumann Do you have the time to look into this? If the students notice this in their dialog development work (as in #125), less experienced users would probably struggle with it even more.

**Comment by timobaumann** [comment]
it's also possible to trigger this without clicking try:
1. embed ASR node in some simple model and click cancel before there is a recognition result.
2. try to run again and it fails in the same way as outlined above.

**Comment by timobaumann** [comment]
interesting: when I wait a while after that, I get: 
```
Exception in thread "PulseAudio Eventloop Thread" java.lang.IllegalStateException: drain failed
        at org.classpath.icedtea.pulseaudio.EventLoop.native_iterate(Native Method)
        at org.classpath.icedtea.pulseaudio.EventLoop.run(EventLoop.java:133)
        at java.lang.Thread.run(Thread.java:748)
```
too bad we don't know what that thread is that is failing.

**Comment by alexanderkoller** [comment]
Wow, that's a weird exception. The [Google search](https://www.google.de/search?q=%22PulseAudio+Eventloop+Thread%22+java.lang.IllegalStateException%3A+drain+failed&oq=%22PulseAudio+Eventloop+Thread%22+java.lang.IllegalStateException%3A+drain+failed&aqs=chrome..69i57.670j0j7&sourceid=chrome&ie=UTF-8) seems to indicate that this is somehow related to audio *playback*. Are we playing back audio in some way before/during/after running the recognizer?

**Comment by timobaumann** [comment]
nope. but I got that only once, so would not read too much into it. 
I'm still debugging the issue. may be related to frontend processing, but I can't really explain how.

**Comment by alexanderkoller** [comment]
Thanks!

**Comment by timobaumann** [comment]
see https://github.com/cmusphinx/sphinx4/issues/87

**Comment by timobaumann** [comment]
I still wonder why this bug only occurred on the very first invocation (i.e., you could cancel on a later invocation if you said something in the first without breaking things). Oh well.

**Comment by alexanderkoller** [comment]
Wow. Cool. Thanks for taking care of this!
