### ISSUE TITLE
Spracherkenner auf Englisch zu stellen funktioniert nicht

### ISSUE THREAD

**Issue by LeHarter** [dialogos-project/dialogos#125]
Hallo,
Wenn im Spracherkenner als Sprache Englisch auswählt, kommt immer, sobald man die Ausführung an diesem Knoten angelangt ist, die Meldung, der Dialog sei beendet.
Mit freundlichen Grüßen,
Leonie Harter
[Englischtest.zip](https://github.com/dialogos-project/dialogos/files/2636774/Englischtest.zip)

**Comment by LeHarter** [comment]
Wenn ich eine Sprachsynthese danach einfüge wird sie nicht mehr ausgeführt. Aber Dialogos neu zu starten funktioniert tatsächlich.
Mit freundlichen Grüßen,
Leonie Harter

**Comment by timobaumann** [comment]
closing as duplicate of #123 .
