### ISSUE TITLE
Refactor model loading funyctionality for use by all plugins (e.g. Sphinx-4 and MaryTTS)

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#15]
It, too, could store its models in the model cache and offer a function for downloading and installing new models when needed.

**Comment by timobaumann** [comment]
in other words: the modelLoader functionality should be generalized rather than living within pocketsphinx. I'll see to that tomorrow so that I can use it from sphinx.

**Comment by timobaumann** [comment]
@alexanderkoller 
What do you think: would it be feasible to use the model loader-to-be to also load and install plugins? that would be very neat. all that needs to happen is for those plugins to somehow end up on the classpath.

**Comment by akoehn** [comment]
At least the installer could be used to install additional plugins (see #4).  Do we need two places for managing such data?

The installer can also be re-run to update the current installation, e.g. to install additional modules and models.

**Comment by timobaumann** [comment]
the code for loading models is all in the Pocketsphinx plugin. For other plugins to be able to use this, it needs to be refactored and put into com.clt.base or Diamant.

**Comment by timobaumann** [comment]
I second @akoehn's opinion that the installer can be used for managing downloads. No use to do it twice.

**Comment by alexanderkoller** [comment]
Taking this off of Milestone 2.0 for now.

**Comment by timobaumann** [comment]
I think we largely agree by now that this should be done via the installer.
