### ISSUE TITLE
Speech Synthesis: Language is changed when dialog is closed

### ISSUE THREAD

**Issue by marcalt94** [dialogos-project/dialogos#154]
Hey,
If I create a Speech Synthesis node and set its language to cmu-slt-hsmm (US-English), the dialog works just fine. If I reload this dialog, the language of said node changes into  cmu-slt-hsmm <not available> and I have to change it back to make the dialog work again.
I attached a .zip archive with a small minimal example so you can test it for yourselves.
[mini_bsp.zip](https://github.com/dialogos-project/dialogos/files/2777005/mini_bsp.zip)

**Comment by timobaumann** [comment]
change it back to what? to the name including US-English?

**Comment by timobaumann** [comment]
most likely fixed with ec4d1a6.
