### ISSUE TITLE
Can't open files from previous versions

### ISSUE THREAD

**Issue by TheresaSchmidt** [dialogos-project/dialogos#157]
Version 2.1.0 can't open dialogues that were created with previous versions of DialogOS. Files created within v2.1.0 work fine.

This is the error message when trying to open a file:
![grafik](https://user-images.githubusercontent.com/36304889/51778530-7d754780-2102-11e9-8d00-d63b3985d434.png)

**Comment by alexanderkoller** [comment]
Wow, this is a surprising bug. Let me look into this.

**Comment by alexanderkoller** [comment]
I can't reproduce this - when I try to open an old dialog with 2.1, it is opened correctly. Could you attach the dialog that you can't open with 2.1?

**Comment by TheresaSchmidt** [comment]
This one, for example. But I haven't found one that works, yet.
[clienttest.zip](https://github.com/dialogos-project/dialogos/files/2798895/clienttest.zip)

**Comment by TheresaSchmidt** [comment]
Now I have. The one that opens doesn't contain a speech recognition node. Does that help?

**Comment by lckr** [comment]
I experience the same behavior under version 2.1 on Linux.

**Comment by akoehn** [comment]
What components did you install?  All or only a subset?

**Comment by TheresaSchmidt** [comment]
All of them

**Comment by akoehn** [comment]
New installation or update?

**Comment by TheresaSchmidt** [comment]
New installation

**Comment by urpeter** [comment]
the error also occurs for me when trying to open the variable menu, in a new Dialogue
![bildschirmfoto 2019-01-26 um 18 02 02](https://user-images.githubusercontent.com/36850433/51790380-b3630c00-2194-11e9-8ade-00abc16609a9.png)

**Comment by alexanderkoller** [comment]
Fixed in [dialogos-distribution](https://github.com/dialogos-project/dialogos-distribution/commit/16d59943fed63daf94eaf93bc5ce455e99d64a3a). Fix will be part of 2.1.1.
