### ISSUE TITLE
[meta] Have a good bug reporting template

### ISSUE THREAD

**Issue by akoehn** [dialogos-project/dialogos#166]
I think that bug reporting could be streamlined by having a template containing what we expect from a bug report:

Please provide the following information when filing a bug report
 - DialogOS version used
 - was DialogOS installed or compiled?
 - which components were installed, if applicable?
 - attach a minimal example dialogue (if applicable)
 - provide the exact traceback if an exception was thrown
 - what steps are needed to reproduce the error?

Suggestions welcome.

**Comment by timobaumann** [comment]
That would be great. Can you set it up? https://help.github.com/articles/creating-issue-templates-for-your-repository/ describes how to do it.

**Comment by akoehn** [comment]
Okay, I adjusted the default github bug report template.  Feel free to adapt it.

**Comment by timobaumann** [comment]
thanks!
