### ISSUE TITLE
Installer does not install ROS plugin

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#180]
The installer that is generated by the current make-distribution script compiles the ROS plugin and bundles it with the distribution; it is also offered for selection in the installer. But then when DialogOS is started, the ROS plugin and its nodes do not show up. Figure out why and fix it.

It might make sense to move this to the 2.1.2 release if tracking down the bug takes too long.

**Comment by timobaumann** [comment]
the resulting plugins/ROS/ does not contain the dialogos-plugin-ros.jar .

**Comment by timobaumann** [comment]
the resulting plugins/ROS/ does not contain the dialogos-plugin-ros.jar .

**Comment by timobaumann** [comment]
fixable by changing the install4j-file to reference `${compiler:dialogos.version}` rather than 2.1.0 (or whatever it is). Also, a few dependency versions need to be updated in the install4j file.

**Comment by alexanderkoller** [comment]
Works.
