### ISSUE TITLE
Labels in Settings dialog of ROS plugin

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#183]
The labels in the ROS settings dialog (Dialog -> ROS Plugin) don't seem to be localized correctly; see the screenshot below. Can we fix this before the 2.1.1 release? @timobaumann 

<img width="1030" alt="Screen Shot 2019-04-26 at 15 27 15" src="https://user-images.githubusercontent.com/8291392/56811129-51b84980-6838-11e9-96cc-17ee20145df2.png">

**Comment by timobaumann** [comment]
I could do this on Sunday, maybe Saturday. I don't think it's super urgent, in particular given that ROS users are likely to know the lower two environment variable names by heart.

**Comment by alexanderkoller** [comment]
Ok. Then let's leave it like this for 2.1.1 and move it to 2.1.2?
