### ISSUE TITLE
Fix the icon for the ROS plugin

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#184]
The ROS plugin uses an icon that is much larger than for all the other plugins. We should fix it so it is the same size as the others. @timobaumann 

<img width="1030" alt="Screen Shot 2019-04-26 at 15 27 15" src="https://user-images.githubusercontent.com/8291392/56811235-8fb56d80-6838-11e9-9f95-642799bb4911.png">

**Comment by timobaumann** [comment]
I like the size :-)\] (Indeed I would argue that some icons in DialogOS are getting too small given today's screens.)

I think the solution is to prescribe the size of the icon/label/whatever regardless of the actual image size. That's slightly more involved but will be better in the long run. I'd say too much work for 2.1.1

**Comment by timobaumann** [comment]
what I propose will work across all plugins hence I'm removing the plugin:ROS label.

**Comment by alexanderkoller** [comment]
Sure, this will take more than ten minutes of work, which is why I didn't put it in the 2.1.1 milestone. I'll add it to 2.1.2.

I'm okay with any redesign that has consistent icon sizes. Also, it's worth noting that icons are bitmap images, so they can't be scaled up. The quickest fix, while we're talking about a final solution, would still be to scale the ROS icon down to the same size as the others.

Personally, I'd be happy to leave the icon sizes as they are, but put the icons to the left of the labels rather than above them; and left-align the labels. This would look much neater than the current mix of plugins with or without icons and with center-aligned labels.

**Comment by timobaumann** [comment]
standard icons (devices, asr, tts) are now larger, maximum size of 48x48 is enforced. fixed issue with tabs not being scrollable. Hooray large icons!
