### ISSUE TITLE
Add icon to ROS nodes

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos#185]
Currently the ROSInput and ROSOutput nodes are the only ones which don't have an icon. Let's add an icon to keep this uniform.

While we're at it, let's also give the ROS plugin a separate plugin ID so that DialogOS draws a separator line between the ROS nodes and the Sqlite node.

<img width="142" alt="Screen Shot 2019-04-26 at 17 46 26" src="https://user-images.githubusercontent.com/8291392/56820033-3c004f80-684b-11e9-9afd-27ce8af7cc85.png">

**Comment by timobaumann** [comment]
fixed in c13da74 (in the ros repo)
