### ISSUE TITLE
File open dialogue does not work under Java 11

### ISSUE THREAD

**Issue by akoehn** [dialogos-project/dialogos#194]
Steps to reproduce:
 - use java 11
 - clone dialogos
 - `./gradlew run`
 - click on "open dialog"
 - observe the `java.lang.NoClassDefFoundError: javafx/stage/DirectoryChooser`

@timobaumann you worked on the file opener recently, does this have a connection?

**Comment by timobaumann** [comment]
still? duh. I'll try my best this afternoon.
workaround is to open model via commandline.

**Comment by akoehn** [comment]
> workaround is to open model via commandline.

Yep, I did this. That is why I filed #193 :-)

**Comment by timobaumann** [comment]
hopefully fixed by bb6bf7e3b50b9428713786abea44f96d6ce94466 -- can you let me know if this now works for you?

**Comment by akoehn** [comment]
Yes, thanks!
