### ISSUE TITLE
showDialog script function calls swing code from non-swing thread.

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#195]
(at least) in modern linux-JDKs, this leads to the windows only being shown when the dialog is over. Also, showDialog is not described in the wiki.

**Comment by timobaumann** [comment]
also fixed the wiki. it would be interesting to know how many other functions in BuiltinFunctions.java are not covered by the wiki...

**Comment by alexanderkoller** [comment]
I can't be sure of course, but I wouldn't be surprised if showDialog had been left undocumented _because_ there was this known bug with it. :)
