### ISSUE TITLE
how do plugins provide script functions?

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#197]
I don't find an obvious way of adding a "semi-builtin" function to provide additional functionality from a plugin. Any hints? (not the groovy hint, please.)

**Comment by alexanderkoller** [comment]
I don't think this is possible, and it's not clear to me that we want this.

- What syntax would you use to address functions provided by plugins?
- How would you protect against the unavailability of these functions if the plugin is not installed?

Any solution that I can think of seems quite brittle, and I'd be inclined to leave this to advanced users who use Groovy scripts and know what a classpath is.

**Comment by timobaumann** [comment]
* Syntax: the plugin just provides the FunctionDescriptor and the corresponding definition of the function. There's absolutely no need for classnames.
* I don't think a plugin only provides nodes. In fact, there might be things that should be controllable from the script language wrt. to the node types provided by the languages. Think modifying incremental speech synthesis as one example.
* Of course, the plugin needs to be there. But same holds true for the nodes. 

I'm thinking there should be something similar to Node.registerNodeType for script functions that should become available in the language when the plugin is loaded. In fact, the present handling of the "DialogOS-Script-Functions" is beyond weird. I don't see how this would be britte.

I, for one, am a sort-of-advanced user who, lacking documentation on Groovy script, still uses the script language.

**Comment by akoehn** [comment]
> lacking documentation on Groovy

https://groovy-lang.org :-)

**Comment by timobaumann** [comment]
plugins may now provide their own script functions by overriding `Plugin#registerScriptFunctions()` and returning `ExecutableFunctionDescriptor`s that directly contain what's to be computed in `eval()`.
An example of how a plugin might want to use this is given in 7240b67

**Comment by alexanderkoller** [comment]
Here is the documentation on Groovy nodes: https://github.com/dialogos-project/dialogos/wiki/Groovy-Functions
