### ISSUE TITLE
EV3 and NXT not to be found over bluetooth

### ISSUE THREAD

**Issue by Jamesir** [dialogos-project/dialogos#198]
Tried to find an EV3 and an NXT over bluetooth on linux, win7 and win10. Unfortunately they cannot be seen in DialogOS. Although pairing in the mindstorms apps is no problem (of course under win7, 10).
The EV3 and the NXT can be connected to the computer over bluetooth before using DialogOS, but are not seen within the app, regardless of beeing connected to the computer beforehand or not.
As I want to steer a robot by speech for school classes a USB cable is not an option unfortunately.

**Comment by alexanderkoller** [comment]
Hi, I'm glad you're trying the Lego plugins!

Have you seen the [Lego compatibility matrix](https://github.com/dialogos-project/dialogos/wiki/Lego-compatibility-matrix) on the DialogOS Wiki?

Bluetooth for NXT is currently not supported. Neither is Bluetooth for EV3 on Linux. Windows can work for EV3 over Bluetooth, but is a bit finicky. The Wiki page has some tips - do they help?

I would love to get Bluetooth support more robust, but I don't have regular access to an EV3 and can only work on this very intermittently. Perhaps consider a USB connection after all for now?

**Comment by Jamesir** [comment]
Hi,
got it working for the EV3 on my old macbook with osx 10.9 for the fair I attended today. Unfortunately bluetooth for Linux is not supported as the compatibility matrix states. Thanks for the link! Under Win10 I got a connection with DialogOS only once, regardless of connecting with the Lego software beforehand or establishing the linking from the brick or from the PC.
I would apprectiate a more stable way of linking the EV3 over bluetooth to a windows PC or even better to a linux machine. But nevertheless, once it connects, DialogOS is a great way of getting pupils into programming apart from ususal Lego software or python on the EV3 and a great eyecatcher for every visitor!
Keep up the good work!

**Comment by alexanderkoller** [comment]
Yes, I agree that it would be great to improve Lego connectivity.

Given that you seem to have solved your immediate problem and the limitations you mention are covered by other issues, I'll close this issue for now.

Please feel free to post other issues with bugs and ideas for improvements!

**Comment by akoehn** [comment]
@Jamesir do you have something like a blog post, pictures or similar we could link to from the DialogOS website?  It is always nice to show use-cases from people who don't develop DialogOS themselves.
