### ISSUE TITLE
function definitions with mistakes yield weird error messages

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#201]
separately defined DialogOS script functions which have a syntax error (e.g. missing ;) lead to weird error messages in script nodes that call this function (claiming that this function does not exist). a better error message would be helpful. fix would be to try parsing the function not only at runtime but immediately (see #200).

**Comment by alexanderkoller** [comment]
Duplicate of #102 ?

**Comment by timobaumann** [comment]
indeed.
