### ISSUE TITLE
result variable is not shown in GUI, even though it has been set

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#209]
in the sqlite plugin, the dropdown for the results is not shown if we load a dialog from file.
(this also seems to be the case for ROS and potentially other plugins.)

we need to find out what exactly is causing this, as well as how to fix it.
please also document how this is fixed so that we can easily port the fix to other plugins.

**Comment by alexanderkoller** [comment]
This is probably an issue with the readAttribute method. I remember that I struggled with this in the Lego plugin. Maybe see if the code in ReadSensorNode#readAttribute in the EV3 plugin is useful for you.

**Comment by mischa99** [comment]
Thanks for the tip! I tried out the code in ReadSensorNode from EV3 plugin, unfortunately it also has a different way of saving the variable at #writeAttribute, so it's not easy to integrate.

**Comment by timobaumann** [comment]
the ROS plugin would love a similar fix :-)

**Comment by timobaumann** [comment]
@mischa99 , is this fixed with your pull request for plugin:SQLite? If so, can you add similar magic to plugin:ROS?

**Comment by timobaumann** [comment]
fixed by https://github.com/dialogos-project/dialogos-plugin-ros/pull/1 and https://github.com/dialogos-project/dialogos-plugin-sqlite/pull/3 .
