### ISSUE TITLE
Java 14 does not include Pack200 decompression any more.

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#212]
The Installer doesn't work on Java 14 anymore because of https://openjdk.java.net/jeps/367 .
We need to check that the change in github.com:dialogos-project/dialogos-distribution.git:39d5085 fixes this.

**Comment by timobaumann** [comment]
and once checked, release a new revision of DialogOS.

**Comment by alexanderkoller** [comment]
I just built an installer locally, and it works.
