### ISSUE TITLE
add user-facing documentation (as docbook or whatever) to repository

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#44]
build the documentation output formats via gradle

**Comment by alexanderkoller** [comment]
Just added a lightly edited version of the German manual from May 2007 to the Wiki.

**Comment by alexanderkoller** [comment]
We still need to clean up all the hyperlinks to other sections of the manual. Those were not converted automatically. Some became just "?"; one I replaced manually by "XXX"; and others are actual links, but point nowhere.

**Comment by alexanderkoller** [comment]
Also added English version, plus links between corresponding German and English pages. We should double-check that both versions are consistent.

**Comment by alexanderkoller** [comment]
Links in the user-facing documentation now work.

**Comment by alexanderkoller** [comment]
One potential tool for generating a PDF from a Github Wiki: https://github.com/yakivmospan/github-wikito-converter

The following command generates a PDF from only the German manual pages:

```
gwtc --toc ~/Documents/workspace/dialogos.wiki/Handbuch.md ~/Documents/workspace/dialogos.wiki -f pdf
```

However, everything is scaled way too small. How can we fix that?

**Comment by alexanderkoller** [comment]
We need to remember to explain how to [install DialogOS](https://github.com/coli-saar/dialogos/issues/4) and [initial recognizer models](https://github.com/coli-saar/dialogos/issues/49) once those issues are closed.

**Comment by timobaumann** [comment]
fixed long ago, if I'm not mistaken.

**Comment by alexanderkoller** [comment]
No, it's not fixed in the way that I think you requested it last year. :) I added all the documentation to the Wiki, and the Javadoc is now automatically rebuilt by Jitpack, but there is still no way of generating a PDF manual automatically. Personally I could live very well without that, but I thought either you or @akoehn found the PDF important. If you're okay with just the Wiki, please feel free to close again.

**Comment by akoehn** [comment]
I don't feel anything regarding that topic :-)
As the wiki is just a series of Markdown pages, we could just write a short script pasting them into a sensible sequential order and use pandoc or similar to create good-looking documentation (both PDF and HTML).

I think that a sequential ordering of a selected subset might be beneficial to people starting with dialogOS.  I'll have a look at that today.

**Comment by akoehn** [comment]
There is now a script generating a PDF in the dialogos-distribution wiki: https://github.com/dialogos-project/dialogos-distribution/commit/14d03a89a81a2b58cf1d706d6708df75a2d7a898

Seems to look okay to me (at least as a first iteration).

**Comment by timobaumann** [comment]
Thanks @akoehn ! Should we mark this resolved?

**Comment by akoehn** [comment]
I just re-read the original issue report and my solution does something different:  It generates PDFs as part of the release process.  Maybe that is compatible with what you originally intended.

If we mark this as resolved, we will need another issue to track progress as the PDF is at the moment very bare-bones:
 - no cover or title
 - no TOC
 - hyperlinks don't work
 - some markup artifacts are still visible (e.g. hyperlinks ...)

Maybe someone who thought more about books than I wants to work on that? :-)

**Comment by alexanderkoller** [comment]
Hey, come on. You wrote a PhD thesis; you know about books. :)
