### ISSUE TITLE
add groups.io subscription link to webpage

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#86]

**Comment by timobaumann** [comment]
I created a groups.io group. I'll add you as owners once it has been approved.

**Comment by timobaumann** [comment]
https://groups.io/g/dialogos/promote has code that could be added to invite people to use/subscribe to groups.io

**Comment by alexanderkoller** [comment]
@timobaumann I just subscribed to the groups.io group using my Google account. Could you add me as co-owner?

I just assigned myself for adding the promo link to the website.

I've noticed that the group gets a message every time we push a commit to Github or someone posts or responds to an issue. This creates a lot of noise that may make it difficult for a normal user to find the signal that is meaningful for them. Could you turn these messages off, or move them to a subforum if that is possible?

**Comment by akoehn** [comment]
I also think that turning the messages off would be good and wanted to turn them off some time ago but I don't have admin rights for the group as well.

I muted the `#github` tag, but now I also don't get any replies to those messages.

**Comment by timobaumann** [comment]
I have removed commits and added you two as admins.
