### ISSUE TITLE
language switching incomplete

### ISSUE THREAD

**Issue by timobaumann** [dialogos-project/dialogos#96]
switching does not take immediate effect in the DialogOS start screen. 
It's probably just not yet wired up but could be done in the same way as it does for the main window.

**Comment by alexanderkoller** [comment]
I'm not quite sure what this means, but it may be the problem I mentioned in my comment to #95. Please let's not put the language picker back in without talking it through first.

**Comment by timobaumann** [comment]
okay, we can talk now.

**Comment by alexanderkoller** [comment]
I'm about to go to bed. I can't talk now. :)

**Comment by timobaumann** [comment]
yes.
